[general]
abbreviate-tab-names=true
compat-delete='ascii-delete'
display-n=0
history-size=1000
max-tab-name-length=20
mouse-display=true
open-tab-cwd=true
prompt-on-quit=true
quick-open-command-line='gedit %(file_path)s'
quick-open-enable=false
restore-tabs-notify=true
restore-tabs-startup=true
save-tabs-when-changed=true
scroll-keystroke=true
set-window-title=true
tab-ontop=true
use-default-font=true
use-popup=true
use-scrollbar=true
use-trayicon=true
use-vte-titles=true
window-halignment=2
window-height=65
window-losefocus=false
window-refocus=false
window-tabbar=true
window-valignment=1
window-vertical-displacement=0
window-width=32

[keybindings/local]
clipboard-copy='<Primary>c'
clipboard-paste='<Primary>v'
new-tab='<Primary>t'
next-tab='<Primary>bracketleft'
previous-tab='<Primary>braceleft'

[style/background]
transparency=90

[style/font]
allow-bold=true
palette='#000027273131:#D0D01B1B2424:#727289890505:#A5A577770505:#20207575C7C7:#C6C61B1B6E6E:#252591918585:#E9E9E2E2CBCB:#00001E1E2626:#BDBD36361212:#46465A5A6161:#525267676F6F:#707081818383:#58585656B9B9:#818190908F8F:#FCFCF4F4DCDC:#525267676F6F:#FCFCF4F4DCDC'
palette-name='Solarized Light'
